insert into adm_roll values (1, null, 1, 'Proba', 'N', 1  );
insert into adm_roll values (2, null, 2, 'Proba', 'N', 1  );
insert into adm_action values (1, null, 'adm_action', 'adm_action', 1  );
insert into adm_action values (2, null, 'adm_roll', 'adm_roll', 1  );
insert into adm_action values (3, null, 'adm_usergrp', 'adm_usergrp', 1  );
insert into adm_action values (4, null, 'adm_user', 'adm_user', 1  );
insert into adm_action values (5, null, 'dell', 'dell', 1  );
insert into adm_usergrp values (1, null, 'test', 'test', 1  );
insert into adm_user values (1, null, 'adm', 'adm', null, null, null, null, null, 0, 'adm@adm.adm', 1, 1, '20230426 1500', '20230426 1500');
insert into adm_user values (2, null, 'test', 'test', null, null, null, null, null, 0, 'test@adm.adm', 1, 1, '20230426 1500', '20230426 1500');
insert into adm_rollact values (1, null, 1, 1);
insert into adm_rollact values (2, null, 1, 2);
insert into adm_rollact values (3, null, 2, 3);
insert into adm_rollact values (4, null, 1, 4);
insert into adm_rollact values (5, null, 1, 5);
insert into adm_userpermiss values (1, null, 1, 1);
insert into adm_userpermiss values (2, null, 1, 2);
insert into adm_userpermiss values (3, null, 2, 2);